id: PE7E81E81
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Palzang Series
  language: en
  description: 'Texts by the great Dzogchen master Khenchen Ngawang Palzang (ngag
    dbang dpal bzang, 1879–1941), also known as Khenpo Ngakchung:'
  volume:
    2496b50a556e48be97bfd7c3845e059b:
      title: Seeds of the Four Philosophical Schools
      parent: Buddhist Philosophy
    15535b9a2e7745f788036f13d0cfa628:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    b303fbd5b2c44e459721733ba4dbbcf1:
      title: The Five Wisdoms
      parent: Dzogchen
    d3ecabbca62747c1b8d6d19a234700cd:
      title: Prayer to Pema Tötreng Tsal
      parent: Guru Rinpoche Prayers
    0b7c04b914994914897974674b9ba320:
      title: Brief Succession of Lives Prayer
      parent: Prayers
    54e5b22945f14bd59434012aa6408ca1:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    73be7af4e0684e7ba09ac8fce20d23c0:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
    369005c32d9f4e72ad8f382c7ef6ee89:
      title: Prayer to Khenpo Ngawang Palzang
      parent: Prayers
    01de78f2fde5403fae6c3d82da9fb394:
      title: Brief Homage to the Twenty-One Tārās
      parent: Tārā
created_at: '2022-03-01T00:22:24.756701'
last_modified_at: '2022-03-01T00:22:24.756709'
